### PR TITLE
Fix random-access-chrome-file not having same interface as the rest

### LINKED ISSUE #4: Interface mismatch?
Hi

I'm trying to use this as a replacement for random-access-file:

from

https://github.com/dominictarr/flumelog-aligned-offset/blob/master/index.js

to:

https://github.com/dominictarr/flumelog-aligned-offset/blob/master/browser.js

The problem is that at least [mutablefile](https://github.com/random-access-storage/random-access-web/blob/master/index.js#L22) doesn't have the same interface as raf. It seems to return a function, as it needs a () around [RAF](https://github.com/dominictarr/flumelog-aligned-offset/blob/master/inject.js#L11), to work?

### PR DESCRIPTION
**Pull request by arj03**
This fixes #4 for me. I never got mutable file running properly, so I'm currently testing in chromium.

### CODE REVIEW

**Comment by RangerMauve** [comment]
Sweet, thank you!

I'll double check it in Chrome Canary tomorrow and get it merged.

Would you mind posting a minimal reproducible case for what wasn't working for you before?

**Comment by arj03** [comment]
Something like this should do it:

```
var RAF = require('random-access-file')
var file = RAF("test.txt")
console.log(file) // <-- works

var RAW = require('random-access-web')
var file = RAW("test.txt")
console.log(file) // <-- doesn't return a file
```

I updated the PR as I think the way random-access-idb does it is cleaner. RACF support opts, so we can do it this way instead.

**Comment by RangerMauve** [comment]
Oh, I think I understand. The problem is that RAW and RAF expose different options.

RAW exposes a function that takes options and returns a file that takes a file name. This is there so you can configure the database options.

I'd rather keep that interface for this module so that users can configure the file storage and DB options still. However, there's polyraf which has the interface you'd expect: https://www.npmjs.com/package/polyraf

**Comment by arj03** [comment]
Right, thanks a lot @RangerMauve!

**Comment by RangerMauve** [comment]
Good luck @arj03! Lemme know if it works out in the end! 😁

**Pull request closed without merging**
